version: '3'
services:
  nuxt:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: always
    ports:
      - '3000'
  nginx:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - nuxt
